#!/usr/bin/env bash
pathtofile=$1
IP=$2
user=$3
pathprivate=$4
if [[ $# -lt 3 ]]
then
        echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
        exit 1
fi
scp -o StrictHostKeyChecking=no -i "$pathprivate "  "$pathtofile" "$user"@"$IP":~/