#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=1
while [ $i -le 20 ]; do
  echo "$i"

i=$(( i + 1 ));

case $i in

  5)
    echo "bad luck from china"
    ;;
  10)
    echo "bad luck from Japan"
    ;;
  18)
    echo "bad luck from china"
    ;;
esac

done
