#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=1
while [ $i -le 20 ]; do
  echo "$i"



case $i in

  4)
    echo "bad luck from china"
    ;;
  9)
    echo "bad luck from Japan"
    ;;
  17)
    echo "bad luck from china"
    ;;
esac
i=$(( i + 1 ));
done
